input_left		= keyboard_check(vk_left)	or keyboard_check(ord("A"))
input_right		= keyboard_check(vk_right)  or keyboard_check(ord("D"))
input_up		= keyboard_check(vk_up)		or keyboard_check(ord("W"))
input_down		= keyboard_check(vk_down)	or keyboard_check(ord("S"))
input_walk		= keyboard_check(vk_control)
input_run		= keyboard_check(vk_shift)
