input_left		= keyboard_check(vk_left)
input_right		= keyboard_check(vk_right)
input_up		= keyboard_check(vk_up)
input_down		= keyboard_check(vk_down)
input_walk		= keyboard_check(vk_control)
input_run		= keyboard_check(vk_shift)
